{
 "title": "Mobile classification service",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Prometheus status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Requests per munite",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total[$__rate_interval])",
     "legendFormat": "{{handler}} {{method}} {{status}}"
    }
   ]
  },
  {
   "title": "Memory (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "resident_memory"
    },
    {
     "expr": "process_virtual_memory_bytes / 1024 / 1024",
     "legendFormat": "virtual_memory"
    }
   ]
  },
  {
   "title": "Prediction Hist",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "prediction_metric_histogram_bucket",
     "legendFormat": "bucket {{le}}"
    }
   ]
  },
  {
   "title": "CPU Time rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}